baseURL = "http://example.org/"
languageCode = "en-us"
title = "UnlockedDevThoughts"
author = "Stefan von Stein"
theme = "gpt"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
pygmentsUseClasses = true
pygmentsCodeFences = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
